/**
 * This file is automatically generated by @xsolla-zk/tokens
 * Do not edit it manually
 */

export const media = {
  md: {
    minWidth: 768,
  },
  maxMd: {
    maxWidth: 767,
  },
  lg: {
    minWidth: 1024,
  },
  maxLg: {
    maxWidth: 1023,
  },
  xl: {
    minWidth: 1366,
  },
  maxXl: {
    maxWidth: 1365,
  },
};
