/**
 * This file is automatically generated by @xsolla-zk/tokens
 * Do not edit it manually
 */

export const media = {
  md: {
    minWidth: 600,
  },
  maxMd: {
    maxWidth: 599,
  },
  lg: {
    minWidth: 800,
  },
  maxLg: {
    maxWidth: 799,
  },
  xl: {
    minWidth: 1200,
  },
  maxXl: {
    maxWidth: 1199,
  },
};
