packages:
  - '.'

catalog:
  typescript: 5.8.2
  globals: 16.1.0
  prettier: ^3.5.0
  vite: ^6.3.5
  "@types/node": ^22.10.1
  "react-native-svg": 15.8.0

catalogs:
  next15:
    next: 15.3.3
    "eslint-config-next": 15.3.3
  eslint9:
    eslint: 9.26.0
    "@eslint/js": 9.26.0
  typescript-eslint:
    "typescript-eslint": 8.32.1
    "@typescript-eslint/eslint-plugin": 8.32.1
    "@typescript-eslint/parser": 8.32.1
  reactNative:
    "react-native": 0.79.2
    "react-native-web": ^0.20.0
    "@types/react-native": ^0.73.0
  react19:
    react: 19.1.0
    react-dom: 19.1.0
    "@types/react": 19.1.4
    "@types/react-dom": 19.1.4
  tamagui:
    "@tamagui/animate-presence": 1.126.13
    "@tamagui/image-next": 1.126.13
    "@tamagui/next-plugin": 1.126.13
    "@tamagui/next-theme": 1.126.13
    "@tamagui/polyfill-dev": 1.126.13