/**
 * This file is automatically generated by @xsolla-zk/tokens
 * Do not edit it manually
 */
export const accordion = {
  size: {
    medium: {
      header: {
        gap: '$space.200',
      },
    },
  },
  board: {
    medium: {
      frame: {
        paddingLeft: {
          base: '$platform.layout.content-compensation.sm',
          $md: '$platform.layout.content-compensation.md',
          $lg: '$platform.layout.content-compensation.lg',
          $xl: '$platform.layout.content-compensation.xl',
        },
        paddingRight: '$space.200',
        paddingVertical: '$space.200',
        borderRadius: '$radius.500',
      },
      content: {
        minHeight: '$size.0',
      },
    },
  },
};
export const badge = {
  $500: {
    frame: {
      minSize: '$size.250',
      borderRadius: '$radius.300',
      gap: '$space.50',
      paddingHorizontal: '$space.150',
    },
    icon: {
      size: '$size.100',
    },
    label: {
      paddingHorizontal: '$space.100',
      typography: 'compact.300.numeric',
    },
  },
};
export const breadcrumbs = {
  $500: {
    frame: {
      gap: '$space.200',
    },
  },
};
export const button = {
  $200: {
    frame: {
      minSize: '$size.200',
      borderRadius: '$radius.300',
      paddingHorizontal: '$space.100',
      gap: '$space.50',
    },
    icon: {
      size: '$size.100',
    },
    label: {
      paddingHorizontal: '$space.100',
      typography: 'compact.200.accent',
    },
  },
  $300: {
    frame: {
      minSize: '$size.300',
      borderRadius: '$radius.300',
      paddingHorizontal: '$space.200',
      gap: '$space.50',
    },
    icon: {
      size: '$size.100',
    },
    label: {
      paddingHorizontal: '$space.100',
      typography: 'compact.200.accent',
    },
  },
  $400: {
    frame: {
      minSize: '$size.400',
      borderRadius: '$radius.400',
      paddingHorizontal: '$space.250',
      gap: '$space.100',
    },
    icon: {
      size: '$size.150',
    },
    label: {
      paddingHorizontal: '$space.150',
      typography: 'compact.250.accent',
    },
  },
  $500: {
    frame: {
      minSize: '$size.500',
      borderRadius: '$radius.500',
      paddingHorizontal: '$space.300',
      gap: '$space.100',
    },
    icon: {
      size: '$size.150',
    },
    label: {
      paddingHorizontal: '$space.200',
      typography: 'compact.300.accent',
    },
  },
  $600: {
    frame: {
      minSize: '$size.600',
      borderRadius: '$radius.500',
      paddingHorizontal: '$space.350',
      gap: '$space.150',
    },
    icon: {
      size: '$size.200',
    },
    label: {
      paddingHorizontal: '$space.200',
      typography: 'compact.350.accent',
    },
  },
  $700: {
    frame: {
      minSize: '$size.700',
      borderRadius: '$radius.550',
      paddingHorizontal: '$space.400',
      gap: '$space.150',
    },
    icon: {
      size: '$size.200',
    },
    label: {
      paddingHorizontal: '$space.200',
      typography: 'compact.350.accent',
    },
  },
};
export const cell = {
  size: {
    large: {
      frame: {
        gap: '$space.300',
        paddingVertical: '$space.200',
      },
      content: {
        minHeight: '$size.250',
        paddingVertical: '$space.100',
      },
      slot: {
        minHeight: '$size.500',
      },
    },
    medium: {
      frame: {
        gap: '$space.250',
        paddingVertical: '$space.150',
      },
      content: {
        minHeight: '$size.200',
        paddingVertical: '$space.50',
      },
      slot: {
        minHeight: '$size.400',
      },
    },
  },
  addon: {
    gap: '$space.200',
  },
  board: {
    large: {
      frame: {
        paddingHorizontal: {
          base: '$platform.layout.content-compensation.sm',
          $md: '$platform.layout.content-compensation.md',
          $lg: '$platform.layout.content-compensation.lg',
          $xl: '$platform.layout.content-compensation.xl',
        },
        paddingVertical: '$space.200',
        borderRadius: '$radius.550',
      },
      content: {
        minHeight: '$size.700',
      },
    },
    medium: {
      frame: {
        paddingHorizontal: {
          base: '$platform.layout.content-compensation.sm',
          $md: '$platform.layout.content-compensation.md',
          $lg: '$platform.layout.content-compensation.lg',
          $xl: '$platform.layout.content-compensation.xl',
        },
        paddingVertical: '$space.200',
        borderRadius: '$radius.550',
      },
      content: {
        minHeight: '$size.600',
      },
    },
    small: {
      frame: {
        paddingHorizontal: {
          base: '$platform.layout.content-compensation.sm',
          $md: '$platform.layout.content-compensation.md',
          $lg: '$platform.layout.content-compensation.lg',
          $xl: '$platform.layout.content-compensation.xl',
        },
        paddingVertical: '$space.100',
        borderRadius: '$radius.550',
      },
      content: {
        minHeight: '$size.500',
      },
    },
  },
};
export const checkbox = {
  $400: {
    frame: {
      size: '$size.100',
      borderRadius: '$radius.200',
      borderWidth: '$stroke.100',
    },
    icon: {
      size: '$size.80',
    },
  },
  $500: {
    frame: {
      size: '$size.200',
      borderRadius: '$radius.300',
      borderWidth: '$stroke.100',
    },
    icon: {
      size: '$size.100',
    },
  },
  $600: {
    frame: {
      size: '$size.300',
      borderRadius: '$radius.300',
      borderWidth: '$stroke.200',
    },
    icon: {
      size: '$size.150',
    },
  },
};
export const chip = {
  $200: {
    frame: {
      minSize: '$size.200',
      borderRadius: '$radius.300',
      paddingHorizontal: '$space.100',
      gap: '$space.50',
    },
    icon: {
      size: '$size.100',
    },
    label: {
      paddingHorizontal: '$space.100',
      typography: 'compact.200.default',
    },
  },
  $300: {
    frame: {
      minSize: '$size.300',
      borderRadius: '$radius.300',
      paddingHorizontal: '$space.200',
      gap: '$space.50',
    },
    icon: {
      size: '$size.100',
    },
    label: {
      paddingHorizontal: '$space.100',
      typography: 'compact.200.default',
    },
  },
  $400: {
    frame: {
      minSize: '$size.400',
      borderRadius: '$radius.400',
      paddingHorizontal: '$space.250',
      gap: '$space.100',
    },
    icon: {
      size: '$size.150',
    },
    label: {
      paddingHorizontal: '$space.150',
      typography: 'compact.250.default',
    },
  },
  $500: {
    frame: {
      minSize: '$size.500',
      borderRadius: '$radius.500',
      paddingHorizontal: '$space.300',
      gap: '$space.100',
    },
    icon: {
      size: '$size.150',
    },
    label: {
      paddingHorizontal: '$space.200',
      typography: 'compact.300.default',
    },
  },
  $600: {
    frame: {
      minSize: '$size.600',
      borderRadius: '$radius.500',
      paddingHorizontal: '$space.350',
      gap: '$space.150',
    },
    icon: {
      size: '$size.200',
    },
    label: {
      paddingHorizontal: '$space.200',
      typography: 'compact.350.default',
    },
  },
  $700: {
    frame: {
      minSize: '$size.700',
      borderRadius: '$radius.550',
      paddingHorizontal: '$space.400',
      gap: '$space.150',
    },
    icon: {
      size: '$size.200',
    },
    label: {
      paddingHorizontal: '$space.200',
      typography: 'compact.350.default',
    },
  },
};
export const chips = {
  $200: {
    frame: {
      gap: '$space.100',
    },
  },
  $300: {
    frame: {
      gap: '$space.100',
    },
  },
  $400: {
    frame: {
      gap: '$space.100',
    },
  },
  $500: {
    frame: {
      gap: '$space.100',
    },
  },
  $600: {
    frame: {
      gap: '$space.100',
    },
  },
  $700: {
    frame: {
      gap: '$space.100',
    },
  },
};
export const dropdown = {
  $400: {
    frame: {
      marginTop: '$space.200',
      padding: '$space.200',
      borderRadius: '$radius.400',
    },
    content: {
      paddingHorizontal: '$space.200',
    },
  },
  $500: {
    frame: {
      marginTop: '$space.200',
      padding: '$space.200',
      borderRadius: '$radius.500',
    },
    content: {
      paddingHorizontal: '$space.200',
    },
  },
  $600: {
    frame: {
      marginTop: '$space.200',
      padding: '$space.200',
      borderRadius: '$radius.500',
    },
    content: {
      paddingHorizontal: '$space.200',
    },
  },
};
export const field = {
  $400: {
    frame: {
      gap: '$space.100',
    },
    row: {
      gap: '$space.200',
      paddingHorizontal: '$space.350',
    },
    inputs: {
      gap: '$space.100',
    },
    label: {
      typography: 'compact.250.default',
    },
    hint: {
      typography: 'compact.250.default',
    },
  },
  $500: {
    frame: {
      gap: '$space.200',
    },
    row: {
      gap: '$space.200',
      paddingHorizontal: '$space.350',
    },
    inputs: {
      gap: '$space.100',
    },
    label: {
      typography: 'compact.250.default',
    },
    hint: {
      typography: 'compact.250.default',
    },
  },
  $600: {
    frame: {
      gap: '$space.200',
    },
    row: {
      gap: '$space.200',
      paddingHorizontal: '$space.350',
    },
    inputs: {
      gap: '$space.100',
    },
    label: {
      typography: 'compact.250.default',
    },
    hint: {
      typography: 'compact.250.default',
    },
  },
};
export const flexButton = {
  $300: {
    frame: {
      gap: '$space.0',
      minHeight: '$size.100',
    },
    label: {
      typography: 'compact.200.accent',
    },
    icon: {
      size: '$size.100',
    },
  },
  $400: {
    frame: {
      gap: '$space.0',
      minHeight: '$size.150',
    },
    label: {
      typography: 'compact.250.accent',
    },
    icon: {
      size: '$size.150',
    },
  },
  $500: {
    frame: {
      gap: '$space.0',
      minHeight: '$size.150',
    },
    label: {
      typography: 'compact.300.accent',
    },
    icon: {
      size: '$size.150',
    },
  },
  $600: {
    frame: {
      gap: '$space.50',
      minHeight: '$size.200',
    },
    label: {
      typography: 'compact.350.accent',
    },
    icon: {
      size: '$size.200',
    },
  },
};
export const gallery = {
  $500: {
    gap: '$space.100',
  },
};
export const inlineInput = {
  $400: {
    typography: 'compact.250.default',
  },
  $500: {
    typography: 'compact.300.default',
  },
  $600: {
    typography: 'display.500.default',
  },
};
export const input = {
  $400: {
    frame: {
      minSize: '$size.400',
      borderRadius: '$radius.400',
      gap: '$space.100',
      borderWidth: '$stroke.200',
      paddingVertical: '$space.300',
      paddingHorizontal: '$space.350',
    },
    label: {
      typography: 'compact.250.default',
    },
  },
  $500: {
    frame: {
      minSize: '$size.500',
      borderRadius: '$radius.500',
      gap: '$space.100',
      borderWidth: '$stroke.200',
      paddingVertical: '$space.300',
      paddingHorizontal: '$space.350',
    },
    label: {
      typography: 'compact.300.default',
    },
  },
  $600: {
    frame: {
      minSize: '$size.600',
      borderRadius: '$radius.500',
      gap: '$space.150',
      borderWidth: '$stroke.200',
      paddingVertical: '$space.300',
      paddingHorizontal: '$space.350',
    },
    label: {
      typography: 'compact.350.default',
    },
  },
};
export const list = {
  size: {
    $500: {
      frame: {
        gap: '$space.50',
      },
      title: {
        gap: '$space.200',
        typography: 'compact.300.accent',
      },
      subtitle: {
        gap: '$space.200',
        typography: 'compact.250.default',
      },
    },
    $600: {
      frame: {
        gap: '$space.50',
      },
      title: {
        gap: '$space.200',
        typography: 'compact.350.accent',
      },
      subtitle: {
        gap: '$space.200',
        typography: 'compact.250.default',
      },
    },
  },
  board: {
    $500: {
      frame: {
        paddingHorizontal: {
          base: '$platform.layout.content-compensation.sm',
          $md: '$platform.layout.content-compensation.md',
          $lg: '$platform.layout.content-compensation.lg',
          $xl: '$platform.layout.content-compensation.xl',
        },
        paddingVertical: '$space.350',
        borderRadius: '$radius.550',
      },
      content: {
        minHeight: '$size.200',
      },
    },
    $600: {
      frame: {
        paddingHorizontal: {
          base: '$platform.layout.content-compensation.sm',
          $md: '$platform.layout.content-compensation.md',
          $lg: '$platform.layout.content-compensation.lg',
          $xl: '$platform.layout.content-compensation.xl',
        },
        paddingVertical: '$space.350',
        borderRadius: '$radius.550',
      },
      content: {
        minHeight: '$size.200',
      },
    },
  },
};
export const loader = {
  $500: {
    borderWidth: '$stroke.400',
  },
};
export const markdown = {
  h1: {
    paddingTop: '$space.650',
    paddingBottom: '$space.200',
  },
  h2: {
    paddingTop: '$space.550',
    paddingBottom: '$space.200',
  },
  h3: {
    paddingTop: '$space.350',
    paddingBottom: '$space.200',
  },
  h4: {
    paddingTop: '$space.200',
    paddingBottom: '$space.200',
  },
  h5: {
    paddingTop: '$space.0',
    paddingBottom: '$space.200',
  },
  p: {
    paddingTop: '$space.0',
    paddingBottom: '$space.350',
  },
  image: {
    paddingTop: '$space.0',
    paddingBottom: '$space.450',
  },
};
export const modal = {
  $500: {
    frame: {
      marginVertical: {
        base: '$space.350',
        $md: '$space.550',
        $xl: '$space.800',
      },
      marginHorizontal: {
        base: '$platform.layout.margin-horizontal.sm',
        $md: '$platform.layout.margin-horizontal.md',
        $lg: '$platform.layout.margin-horizontal.lg',
        $xl: '$platform.layout.margin-horizontal.xl',
      },
      borderRadius: {
        base: '$radius.600',
        $lg: '$radius.700',
      },
    },
    header: {
      paddingTop: {
        base: '$space.300',
        $lg: '$space.450',
      },
    },
    content: {
      paddingTop: {
        base: '$space.100',
        $lg: '$space.200',
        $xl: '$space.300',
      },
      paddingBottom: {
        base: '$space.350',
        $lg: '$space.450',
        $xl: '$space.550',
      },
    },
    footer: {
      paddingBottom: {
        base: '$platform.layout.margin-horizontal.sm',
        $md: '$platform.layout.margin-horizontal.md',
        $lg: '$platform.layout.margin-horizontal.lg',
        $xl: '$platform.layout.margin-horizontal.xl',
      },
    },
  },
};
export const navBar = {
  size: {
    $500: {
      frame: {
        minHeight: {
          base: '$size.450',
          $lg: '$size.600',
          $xl: '$size.700',
        },
        paddingHorizontal: {
          base: '$platform.layout.margin-horizontal.sm',
          $md: '$platform.layout.margin-horizontal.md',
          $lg: '$platform.layout.margin-horizontal.lg',
          $xl: '$platform.layout.margin-horizontal.xl',
        },
      },
      content: {
        gap: '$space.350',
        paddingHorizontal: {
          base: '$platform.layout.content-compensation.sm',
          $md: '$platform.layout.content-compensation.md',
          $lg: '$platform.layout.content-compensation.lg',
          $xl: '$platform.layout.content-compensation.xl',
        },
      },
      addon: {
        gap: '$space.300',
      },
    },
  },
  center: {
    default: {
      frame: {
        gap: '$space.50',
      },
      title: {
        typography: {
          base: 'compact.300.accent',
          $lg: 'display.350.accent',
          $xl: 'display.400.accent',
        },
      },
      subtitle: {
        typography: {
          base: 'compact.250.default',
          $lg: 'compact.300.default',
        },
      },
    },
    prominent: {
      frame: {
        gap: '$space.50',
      },
      title: {
        typography: {
          base: 'display.400.accent',
          $lg: 'display.450.accent',
          $xl: 'display.500.accent',
        },
      },
      subtitle: {
        typography: {
          base: 'compact.250.default',
          $lg: 'compact.300.default',
        },
      },
    },
  },
};
export const pimple = {
  $200: {
    frame: {
      minSize: '$size.40',
      borderRadius: '$radius.999',
      paddingHorizontal: '$space.0',
    },
    icon: {
      size: '$size.40',
    },
    label: {
      typography: 'compact.150.accent-numeric',
    },
  },
  $300: {
    frame: {
      minSize: '$size.80',
      borderRadius: '$radius.999',
      paddingHorizontal: '$space.50',
    },
    icon: {
      size: '$size.40',
    },
    label: {
      typography: 'compact.150.accent-numeric',
    },
  },
  $400: {
    frame: {
      minSize: '$size.100',
      borderRadius: '$radius.999',
      paddingHorizontal: '$space.50',
    },
    icon: {
      size: '$size.60',
    },
    label: {
      typography: 'compact.150.accent-numeric',
    },
  },
  $500: {
    frame: {
      minSize: '$size.150',
      borderRadius: '$radius.999',
      paddingHorizontal: '$space.100',
    },
    icon: {
      size: '$size.80',
    },
    label: {
      typography: 'compact.200.accent-numeric',
    },
  },
  $600: {
    frame: {
      minSize: '$size.200',
      borderRadius: '$radius.999',
      paddingHorizontal: '$space.100',
    },
    icon: {
      size: '$size.100',
    },
    label: {
      typography: 'compact.250.accent-numeric',
    },
  },
  $700: {
    frame: {
      minSize: '$size.300',
      borderRadius: '$radius.999',
      paddingHorizontal: '$space.200',
    },
    icon: {
      size: '$size.100',
    },
    label: {
      typography: 'compact.300.accent-numeric',
    },
  },
};
export const progressBar = {
  $500: {
    frame: {
      height: '$size.20',
      borderRadius: '$radius.999',
    },
  },
};
export const radio = {
  $400: {
    frame: {
      size: '$size.100',
      borderWidth: '$stroke.100',
    },
    icon: {
      size: '$size.80',
    },
  },
  $500: {
    frame: {
      size: '$size.200',
      borderWidth: '$stroke.100',
    },
    icon: {
      size: '$size.100',
    },
  },
  $600: {
    frame: {
      size: '$size.300',
      borderWidth: '$stroke.200',
    },
    icon: {
      size: '$size.150',
    },
  },
};
export const richIcon = {
  $100: {
    frame: {
      minSize: '$size.100',
    },
    icon: {
      size: '$size.80',
    },
    label: {
      typography: 'compact.150.numeric',
      paddingHorizontal: '$space.50',
      paddingTop: '$space.25',
    },
  },
  $200: {
    frame: {
      minSize: '$size.200',
    },
    icon: {
      size: '$size.100',
    },
    label: {
      typography: 'compact.200.numeric',
      paddingHorizontal: '$space.100',
      paddingTop: '$space.25',
    },
  },
  $300: {
    frame: {
      minSize: '$size.300',
    },
    icon: {
      size: '$size.150',
    },
    label: {
      typography: 'compact.200.numeric',
      paddingHorizontal: '$space.100',
      paddingTop: '$space.25',
    },
  },
  $400: {
    frame: {
      minSize: '$size.400',
    },
    icon: {
      size: '$size.200',
    },
    label: {
      typography: 'compact.250.numeric',
      paddingHorizontal: '$space.150',
      paddingTop: '$space.25',
    },
  },
  $500: {
    frame: {
      minSize: '$size.500',
    },
    icon: {
      size: '$size.250',
    },
    label: {
      typography: 'compact.300.numeric',
      paddingHorizontal: '$space.200',
      paddingTop: '$space.50',
    },
  },
  $600: {
    frame: {
      minSize: '$size.600',
    },
    icon: {
      size: '$size.300',
    },
    label: {
      typography: 'compact.350.numeric',
      paddingHorizontal: '$space.200',
      paddingTop: '$space.50',
    },
  },
  $700: {
    frame: {
      minSize: '$size.700',
    },
    icon: {
      size: '$size.350',
    },
    label: {
      typography: 'compact.350.numeric',
      paddingHorizontal: '$space.200',
      paddingTop: '$space.50',
    },
  },
  $800: {
    frame: {
      minSize: '$size.800',
    },
    icon: {
      size: '$size.400',
    },
    label: {
      typography: 'compact.400.numeric',
      paddingHorizontal: '$space.200',
      paddingTop: '$space.50',
    },
  },
  $900: {
    frame: {
      minSize: '$size.900',
    },
    icon: {
      size: '$size.450',
    },
    label: {
      typography: 'compact.400.numeric',
      paddingHorizontal: '$space.200',
      paddingTop: '$space.100',
    },
  },
};
export const segment = {
  $400: {
    frame: {
      minSize: '$size.300',
      borderRadius: '$radius.300',
      borderWidth: '$stroke.100',
      paddingHorizontal: '$space.200',
      gap: '$space.50',
    },
    icon: {
      size: '$size.100',
    },
    label: {
      paddingHorizontal: '$space.100',
      typography: 'compact.200.accent',
    },
  },
  $500: {
    frame: {
      minSize: '$size.400',
      borderRadius: '$radius.400',
      borderWidth: '$stroke.100',
      paddingHorizontal: '$space.250',
      gap: '$space.100',
    },
    icon: {
      size: '$size.150',
    },
    label: {
      paddingHorizontal: '$space.150',
      typography: 'compact.250.accent',
    },
  },
  $600: {
    frame: {
      minSize: '$size.500',
      borderRadius: '$radius.400',
      borderWidth: '$stroke.100',
      paddingHorizontal: '$space.300',
      gap: '$space.100',
    },
    icon: {
      size: '$size.150',
    },
    label: {
      paddingHorizontal: '$space.200',
      typography: 'compact.300.accent',
    },
  },
  $700: {
    frame: {
      minSize: '$size.600',
      borderRadius: '$radius.500',
      borderWidth: '$stroke.100',
      paddingHorizontal: '$space.350',
      gap: '$space.150',
    },
    icon: {
      size: '$size.200',
    },
    label: {
      paddingHorizontal: '$space.200',
      typography: 'compact.350.accent',
    },
  },
};
export const segmentedControl = {
  $400: {
    frame: {
      paddingHorizontal: '$space.100',
      paddingVertical: '$space.100',
      borderRadius: '$radius.400',
      borderWidth: '$stroke.100',
    },
  },
  $500: {
    frame: {
      paddingHorizontal: '$space.100',
      paddingVertical: '$space.100',
      borderRadius: '$radius.500',
      borderWidth: '$stroke.100',
    },
  },
  $600: {
    frame: {
      paddingHorizontal: '$space.100',
      paddingVertical: '$space.100',
      borderRadius: '$radius.500',
      borderWidth: '$stroke.100',
    },
  },
  $700: {
    frame: {
      paddingHorizontal: '$space.100',
      paddingVertical: '$space.100',
      borderRadius: '$radius.550',
      borderWidth: '$stroke.100',
    },
  },
};
export const semanticText = {
  headerXl: {
    paddingTop: '$space.0',
    paddingBottom: {
      base: '$space.150',
      $lg: '$space.200',
    },
    typography: {
      base: 'display.500.accent',
      $lg: 'display.600.accent',
      $xl: 'display.700.accent',
    },
  },
  headerL: {
    paddingTop: {
      base: '$space.50',
      $xl: '$space.100',
    },
    paddingBottom: '$space.200',
    typography: {
      base: 'display.450.accent',
      $lg: 'display.500.accent',
      $xl: 'display.600.accent',
    },
  },
  headerM: {
    paddingTop: '$space.100',
    paddingBottom: '$space.200',
    typography: {
      base: 'display.400.accent',
      $lg: 'display.450.accent',
      $xl: 'display.500.accent',
    },
  },
  headerS: {
    paddingTop: {
      base: '$space.150',
      $lg: '$space.50',
      $xl: '$space.100',
    },
    paddingBottom: {
      base: '$space.250',
      $lg: '$space.200',
    },
    typography: {
      base: 'display.350.accent',
      $lg: 'display.400.accent',
      $xl: 'display.450.accent',
    },
  },
  headerXs: {
    paddingTop: {
      base: '$space.150',
      $lg: '$space.50',
      $xl: '$space.100',
    },
    paddingBottom: '$space.250',
    typography: {
      base: 'compact.300.accent',
      $lg: 'display.350.accent',
      $xl: 'display.400.accent',
    },
  },
  paragraphL: {
    paddingTop: '$space.100',
    paddingBottom: '$space.200',
    typography: {
      base: 'text.350.default',
      $lg: 'text.400.default',
    },
  },
  paragraphM: {
    paddingTop: {
      base: '$space.0',
      $lg: '$space.100',
    },
    paddingBottom: {
      base: '$space.100',
      $lg: '$space.200',
    },
    typography: {
      base: 'text.300.default',
      $lg: 'text.350.default',
    },
  },
  paragraphS: {
    paddingTop: '$space.0',
    paddingBottom: '$space.100',
    typography: {
      base: 'text.250.default',
      $lg: 'text.300.default',
    },
  },
};
export const separator = {
  $500: {
    borderWidth: '$stroke.100',
  },
};
export const slider = {
  $500: {
    frame: {
      height: '$size.20',
      borderRadius: '$radius.999',
    },
    knob: {
      size: '$size.150',
      borderWidth: '$stroke.100',
    },
  },
};
export const snackBar = {
  $500: {
    frame: {
      maxWidth: 400,
      borderRadius: '$radius.550',
      paddingTop: '$space.200',
      paddingBottom: '$space.200',
      paddingRight: '$space.650',
      paddingLeft: '$space.300',
    },
    content: {
      frame: {
        gap: '$space.300',
      },
      icon: {
        minHeight: '$space.800',
      },
      description: {
        frame: {
          paddingVertical: '$space.100',
          gap: '$space.100',
        },
        list: {
          gap: '$space.50',
        },
        actions: {
          gap: '$space.350',
        },
      },
    },
  },
};
export const switchComponent = {
  $600: {
    frame: {
      borderRadius: '$radius.999',
      borderWidth: '$stroke.200',
      padding: '$space.50',
    },
    knob: {
      size: '$size.200',
      borderRadius: '$radius.999',
    },
  },
};
export const tabs = {
  $300: {
    frame: {
      gap: '$space.300',
    },
  },
  $400: {
    frame: {
      gap: '$space.350',
    },
  },
  $500: {
    frame: {
      gap: '$space.400',
    },
  },
  $600: {
    frame: {
      gap: '$space.400',
    },
  },
  $700: {
    frame: {
      gap: '$space.450',
    },
  },
};
export const notificationProvider = {
  $500: {
    marginHorizontal: {
      base: '$platform.layout.margin-horizontal.sm',
      $md: '$platform.layout.margin-horizontal.md',
      $lg: '$platform.layout.margin-horizontal.lg',
      $xl: '$platform.layout.margin-horizontal.xl',
    },
    marginVertical: {
      base: '$space.450',
      $md: '$space.650',
      $xl: '$space.900',
    },
  },
};
export const tabBar = {
  $500: {
    tab: {
      minHeight: '$size.600',
      gap: '$space.100',
    },
    icon: {
      size: '$size.250',
    },
    label: {
      typography: 'compact.200.default',
    },
  },
};
export const tab = {
  $300: {
    frame: {
      minSize: '$size.300',
      gap: '$space.0',
    },
    icon: {
      size: '$size.100',
    },
    label: {
      typography: 'compact.200.accent',
    },
    line: {
      height: '$size.20',
      borderTopLeftRadius: '$radius.999',
      borderTopRightRadius: '$radius.999',
      borderBottomLeftRadius: '$radius.0',
      borderBottomRightRadius: '$radius.0',
    },
  },
  $400: {
    frame: {
      minSize: '$size.400',
      gap: '$space.0',
    },
    icon: {
      size: '$size.150',
    },
    label: {
      typography: 'compact.250.accent',
    },
    line: {
      height: '$size.20',
      borderTopLeftRadius: '$radius.999',
      borderTopRightRadius: '$radius.999',
      borderBottomLeftRadius: '$radius.0',
      borderBottomRightRadius: '$radius.0',
    },
  },
  $500: {
    frame: {
      minSize: '$size.500',
      gap: '$space.0',
    },
    icon: {
      size: '$size.150',
    },
    label: {
      typography: 'compact.300.accent',
    },
    line: {
      height: '$size.20',
      borderTopLeftRadius: '$radius.999',
      borderTopRightRadius: '$radius.999',
      borderBottomLeftRadius: '$radius.0',
      borderBottomRightRadius: '$radius.0',
    },
  },
  $600: {
    frame: {
      minSize: '$size.600',
      gap: '$space.50',
    },
    icon: {
      size: '$size.200',
    },
    label: {
      typography: 'compact.350.accent',
    },
    line: {
      height: '$size.20',
      borderTopLeftRadius: '$radius.999',
      borderTopRightRadius: '$radius.999',
      borderBottomLeftRadius: '$radius.0',
      borderBottomRightRadius: '$radius.0',
    },
  },
  $700: {
    frame: {
      minSize: '$size.700',
      gap: '$space.50',
    },
    icon: {
      size: '$size.200',
    },
    label: {
      typography: 'compact.350.accent',
    },
    line: {
      height: '$size.20',
      borderTopLeftRadius: '$radius.999',
      borderTopRightRadius: '$radius.999',
      borderBottomLeftRadius: '$radius.0',
      borderBottomRightRadius: '$radius.0',
    },
  },
};
export const toast = {
  $500: {
    frame: {
      borderRadius: '$radius.500',
      paddingTop: '$space.100',
      paddingBottom: '$space.100',
      paddingRight: '$space.300',
      paddingLeft: '$space.100',
      gap: '$space.250',
    },
  },
};
export const components = {
  accordion,
  badge,
  breadcrumbs,
  button,
  cell,
  checkbox,
  chip,
  chips,
  dropdown,
  field,
  flexButton,
  gallery,
  inlineInput,
  input,
  list,
  loader,
  markdown,
  modal,
  navBar,
  pimple,
  progressBar,
  radio,
  richIcon,
  segment,
  segmentedControl,
  semanticText,
  separator,
  slider,
  snackBar,
  switchComponent,
  tabs,
  notificationProvider,
  tabBar,
  tab,
  toast,
};
