/**
 * This file is automatically generated by @xsolla-zk/tokens
 * Do not edit it manually
 */

export const fonts = {
  display: {
    family: 'Onest',
    size: {
      '350': 18,
      '400': 22,
      '450': 28,
      '500': 32,
      '600': 36,
      '650': 40,
      '700': 48,
    },
    lineHeight: {
      '350': 22,
      '400': 26,
      '450': 32,
      '500': 38,
      '600': 42,
      '650': 48,
      '700': 56,
    },
    weight: {
      default: '500',
      numeric: '500',
      accent: '600',
      'accent-numeric': '600',
    },
  },
  text: {
    family: 'Onest',
    size: {
      '150': 10,
      '200': 12,
      '250': 14,
      '300': 16,
      '350': 18,
      '400': 22,
    },
    lineHeight: {
      '150': 14,
      '200': 16,
      '250': 20,
      '300': 22,
      '350': 24,
      '400': 30,
    },
    weight: {
      default: '500',
      numeric: '500',
      accent: '600',
      'accent-numeric': '600',
    },
  },
  compact: {
    family: 'Onest',
    size: {
      '150': 10,
      '200': 12,
      '250': 14,
      '300': 16,
      '350': 18,
      '400': 22,
    },
    lineHeight: {
      '150': 12,
      '200': 14,
      '250': 16,
      '300': 18,
      '350': 22,
      '400': 26,
    },
    weight: {
      default: '500',
      numeric: '500',
      accent: '600',
      'accent-numeric': '600',
    },
  },
};
