/**
 * This file is automatically generated by @xsolla-zk/tokens
 * Do not edit it manually
 */
export const ios = {
  'layout.col-number.sm': 1,
  'layout.col-number.md': 6,
  'layout.col-number.lg': 6,
  'layout.col-number.xl': 6,
  'layout.gutter.sm': 0,
  'layout.gutter.md': 0,
  'layout.gutter.lg': 0,
  'layout.gutter.xl': 0,
  'layout.margin-horizontal.sm': 4,
  'layout.margin-horizontal.md': 20,
  'layout.margin-horizontal.lg': 24,
  'layout.margin-horizontal.xl': 48,
  'layout.content-compensation.sm': 16,
  'layout.content-compensation.md': 16,
  'layout.content-compensation.lg': 16,
  'layout.content-compensation.xl': 16,
};
export const android = {
  'layout.col-number.sm': 12,
  'layout.col-number.md': 12,
  'layout.col-number.lg': 12,
  'layout.col-number.xl': 12,
  'layout.gutter.sm': 16,
  'layout.gutter.md': 16,
  'layout.gutter.lg': 16,
  'layout.gutter.xl': 24,
  'layout.margin-horizontal.sm': 4,
  'layout.margin-horizontal.md': 20,
  'layout.margin-horizontal.lg': 24,
  'layout.margin-horizontal.xl': 48,
  'layout.content-compensation.sm': 16,
  'layout.content-compensation.md': 16,
  'layout.content-compensation.lg': 16,
  'layout.content-compensation.xl': 16,
};
export const web = {
  'layout.col-number.sm': 12,
  'layout.col-number.md': 12,
  'layout.col-number.lg': 12,
  'layout.col-number.xl': 12,
  'layout.gutter.sm': 16,
  'layout.gutter.md': 16,
  'layout.gutter.lg': 16,
  'layout.gutter.xl': 24,
  'layout.margin-horizontal.sm': 4,
  'layout.margin-horizontal.md': 20,
  'layout.margin-horizontal.lg': 24,
  'layout.margin-horizontal.xl': 48,
  'layout.content-compensation.sm': 16,
  'layout.content-compensation.md': 16,
  'layout.content-compensation.lg': 16,
  'layout.content-compensation.xl': 16,
};
export const platform = { ios, android, web };
